config/routes.rb
Rails.application.routes.draw do

  resources :pages

  root 'pages#index'
   get "/varsity_members/report", to: "varsity_members#report", as: :report_varsity_members
   get "/varsity_members/report_email", to: "varsity_members#report_email", as: :report_email_varsity_members
  resources :varsity_members
   get "/debt_settlements/:id/confirm", to: "debt_settlements#confirm", as: :category_confirm
  resources :tryout_intents
  resources :training_activities
  resources :debt_settlements
  resources :competitions
  resources :contingents
  resources :acquired_quota_points
  resources :competition_debts
  devise_for :officer_in_charges, :controllers => { :registrations => "registrations" } #, :path_names => { :sign_up => "debate" }
  devise_scope :officer_in_charge do
     get 'debate' => 'devise/registrations#new', :as => :new_officer_in_charges_registration 
     post 'debate' => 'devise/registrations#create', :as => :officer_in_charges_registration
  end
  match '/officer_in_charges/:id' => 'officer_in_charges#destroy', :via => :delete, :as => :admin_destroy_user
  get "/officer_in_charges/index", to: "officer_in_charges#index", as: :officer_in_charges
  get "/officer_in_charges/make", to: "officer_in_charges#make", as: :make_officer_in_charges

end

app/models/varsity_member.rb
class VarsityMember < ActiveRecord::Base
		TRACK = ["Debater", "Adjudicator", "Debater and Adjudicator"]
	POSITION = ["Contingent Debater", "Contingent Adjudicator", "Non-contingent"]

	validates :vm_id, length: { is: 6 }, :uniqueness => { :message => "ID number already exist" }, numericality: true
	validates :first_name, length: { maximum: 30}
	validates :last_name,  length: { maximum: 30}
	validates :year,  length: { is: 1 }
	validates :course, length: { maximum: 15 }
	validates :contact_number, length: { is: 11 }
	validates :email_address,  length: { maximum: 40 }, :uniqueness => { :message => "ID number already exist" }
	validates :varsity_track, inclusion: { in: TRACK }
	validates :debater_position, inclusion: { in: POSITION }
	validates :total_debt, length: { maximum: 7 }, numericality: true
	validates :total_acquired_quota_points, length: { maximum: 5 }, numericality: true

	
	has_many :debt_settlements 
	has_many :competition_debts
	has_many :acquired_quota_points, through: :activity_members
	has_many :activity_members, :dependent => :destroy
	has_many :tryout_intents
	has_many :competitons, through: :competition_debts

	validate :cannot_be_wrong
	
	def cannot_be_wrong

		if self.first_name == "" 
	       	errors.add(:first_name, "Cannot be blank!")
		end

		if self.last_name == "" 
	       	errors.add(:last_name, "Cannot be blank!")
		end

		if self.course == "" 
	       	errors.add(:course, "Cannot be blank!")
		end

		if self.email_address == "" 
	       	errors.add(:email_address, "Cannot be blank!")
		end

		if self.contact_number == "" 
			errors.add(:contact_number, "Cannot be blank!")
		else
	 		if self.contact_number.length != 11
	     		errors.add(:contact_number, "Must contain valid cellphone number! (11 digits)")
	    	end
	    end
		if self.vm_id == ""
			errors.add(:vm_id, "Cannot be blank!")
		else
			if !self.vm_id.nil?
	    		if self.vm_id > 999999
	      			errors.add(:vm_id, "Must contain valid ID Number (6 digits)")
	    		end
	    	end
		end
	end

	before_validation :load_default

	 def load_default
   		if self.new_record?
        self.total_debt = 0.00
        self.total_acquired_quota_points = 0.00
      end
   end


	def to_s
		self.first_name + " " + self.last_name
	end

	# def calculate_total_debt
	# 	competition = Competition.find(self.competition_id)
	# 	vm = VarsityMember.find(self.varsity_member_id)

	# 	position = vm.debater_positon

		

	# 	competiton.avm.total_acquired_quota_points 
	# 	money = competition.quota_point_monetary_value


	# 	selfVarsityMember.all.each do |member|
	# 		member.total_debt = member.total_debt + (member.total_acquired_quota_points * member.competitons
	# 	end
	# end

	
end

app/controllers/varsity_members_controller.rb
class VarsityMembersController < ApplicationController
   load_and_authorize_resource
  def index

    if params[:total_debt] == "0"
      @varsity_members = VarsityMember.where("total_debt = 0")
    elsif params[:total_debt] == "1"
       @varsity_members = VarsityMember.where("total_debt > 0")
    else
      @varsity_members = VarsityMember.all 
    end
    render(:template => "varsity_members/index")
  end

  def report_email
    @varsity_members = VarsityMember.all
    @role = Role.find_by(name: "Administrator")
    @officer = OfficerInCharge.find_by(role_id: @role.id)
    @admin = OfficerInCharge.find(@officer.id)
    UserMailer.report_email(@admin, @varsity_members).deliver!
    redirect_to varsity_members_path()
    flash[:notice] = 'Email has been sent!'
  end

  def report
    @varsity_members = VarsityMember.all 

     respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "report_varsity_members_path"   # Excluding ".pdf" extension.
      end
    end
  end

  def show
    @varsity_member = VarsityMember.find(params[:id])
  end

  def new
    @varsity_member = VarsityMember.new

    render(:template => "varsity_members/new")
  end

  def create
    @varsity_member = VarsityMember.new(varsity_member_params)

    if @varsity_member.save
      redirect_to varsity_member_path(@varsity_member.id)
    else
      render(:template => "varsity_members/new")
    end
  end

  def edit
    @varsity_member = VarsityMember.find(params[:id])

    render(:templace => "varsity_members/edit")
  end

  def update
    @varsity_member = VarsityMember.find(params[:id])

    if @varsity_member.update(varsity_member_params)
      redirect_to varsity_member_path(@varsity_member)
    else
      render(:template => "varsity_members/edit")
    end
  end

  def destroy
    @varsity_member = VarsityMember.find(params[:id])
    @varsity_member.destroy!
    redirect_to varsity_members_path
  end

  def varsity_member_params
    params.require(:varsity_member).permit!
  end

end

app/helpers/varsity_members_helper.rb
module VarsityMembersHelper
end

app/views/varsity_members/_form.html.erb
<%= simple_form_for(@varsity_member) do |f| %>
  <%= f.error_notification %>

<div class="container">
  <div class="row">
    <div class="col-md-6">

  <div class="form-inputs">
    <%= f.input :vm_id, :label => "ID", placeholder: '100001' %>
  </div>

  <div class="form-inputs">
    <%= f.input :first_name, placeholder: 'Juan' %>
  </div>

  <div class="form-inputs">
    <%= f.input :last_name, placeholder: 'Dela Cruz' %>
  </div>

  <div class="form-inputs">
    <%= f.input :year, :collection => 1..5, :as => :select, :include_blank => false %>
  </div>

  <div class="form-inputs">
    <%= f.input :course, placeholder: 'BS MIS' %>
  </div>

  <div class="form-inputs">
    <%= f.input :contact_number, placeholder: '09XX-XXX-XXXX' %>
  </div>

  <div class="form-inputs">
    <%= f.input :email_address, placeholder: 'user@domain.com' %>
  </div>

  <div class="form-inputs">
    <%= f.input :varsity_track, :as => :select, :collection => VarsityMember::TRACK, :include_blank => false %>
  </div>

  <div class="form-inputs">
    <%= f.input :debater_position, :as => :select, :collection => VarsityMember::POSITION, :include_blank => false, priority: [ "Non-contingent" ] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, data: { confirm: 'Are you sure?'}%>
  </div>

    </div>
  </div> 
</div>
<% end %>

app/views/varsity_members/create.html.erb
<h1>VarsityMembers#create</h1>
<p>Find me in app/views/varsity_members/create.html.erb</p>

app/views/varsity_members/destroy.html.erb
<h1>VarsityMembers#destroy</h1>
<p>Find me in app/views/varsity_members/destroy.html.erb</p>

app/views/varsity_members/edit.html.erb
<h1>Editing Varsity Member</h1>

<%= render 'form' %>

<br>
<div style="margin-left: 1.3%;">
	<%= link_to 'Back', varsity_members_path, class: "btn btn-default" %>
</div>

app/views/varsity_members/email_report.pdf.erb
<h1>Listing Varsity Members</h1>
<div class="responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th style="margin: 0 10px;">ID</th>
        <th style="margin: 0 100px;">Last Name</th>
        <th>Varsity Track</th>
        <th>Debater Position</th>
        <th>Acquired QP</th>
        <th>Total Debt</th>
        <th colspan="10"></th>
      </tr>
    </thead>

    <tbody>
      <% @varsity_members.each do |varsity_member| %>
        <tr>
          <td><%= varsity_member.vm_id %></td>
          <td><%= varsity_member.last_name %></td>
          <td><%= varsity_member.varsity_track %></td>
          <td><%= varsity_member.debater_position %></td>
          <td style="text-align: right;"><%= varsity_member.total_acquired_quota_points %></td>
          <td style="text-align: right;"><%= varsity_member.total_debt %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/varsity_members/index.html.erb
<h1>Listing Varsity Members</h1>
<p>
<a class="btn btn-default" href="/varsity_members">All</a>
<%= link_to "No Debt", varsity_members_path(:total_debt=>"0"), class: "btn btn-default" %>
<%= link_to "With Debt", varsity_members_path(:total_debt=>"1"), class: "btn btn-default" %>
</p>
<div class="responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Year</th>
        <th>Course</th>
        <th>Contact Number</th>
        <th>E-mail Address</th>
        <th>Varsity Track</th>
        <th>Debater Position</th>
        <th style= "text-align: right;">Total Debt</th>
        <th style= "text-align: right;">Total Acquired Quota Points</th>
        <th colspan="10"></th>
      </tr>
    </thead>

    <tbody>
      <% @varsity_members.each do |varsity_member| %>
        <tr>
          <td><%= varsity_member.vm_id %></td>
          <td><%= varsity_member.first_name %></td>
          <td><%= varsity_member.last_name %></td>
          <td><%= varsity_member.year %></td>
          <td><%= varsity_member.course %></td>
          <td><%= varsity_member.contact_number %></td>
          <td><%= varsity_member.email_address %></td>
          <td><%= varsity_member.varsity_track %></td>
          <td><%= varsity_member.debater_position %></td>
          <td style= "text-align: right;"><%= number_to_currency(varsity_member.total_debt, :unit => "Php") %></td>
          <td style= "text-align: right;"><%= number_with_precision(varsity_member.total_acquired_quota_points, precision: 2, delimiter: ',') %></td>
          <!-- <td><button class="btn btn-default" type="submit"><%= link_to 'Show', varsity_member %></button></td> -->
          <% if officer_in_charge_signed_in? %>
              <% @role = Role.find(current_officer_in_charge.role_id).name %>
              
              <% if @role == "Office of Training and Varsity"%>
                <td><%= link_to 'Edit', edit_varsity_member_path(varsity_member), class: "btn btn-warning" %></td>
                <td><%= link_to 'Delete', varsity_member, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>

              <% elsif @role == "Office of Finance" %>
                <td><%= link_to 'Pay', new_debt_settlement_path, class: "btn btn-primary"%></td>
                <td><%= link_to 'Add Debt', new_competition_debt_path(), class: "btn btn-danger" %></td>
              <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% if officer_in_charge_signed_in? %>
      <% @role = Role.find(current_officer_in_charge.role_id).name %>

      <% if @role == "Office of Training and Varsity"%>
        <%= link_to 'New Varsity Member', new_varsity_member_path, class: "btn btn-default" %>
      <% end %>
<% end %>

<br>
<br>

<% if officer_in_charge_signed_in? %>
    <% @role = Role.find(current_officer_in_charge.role_id).name %>
        <% if @role == "Office of Training and Varsity" %>
          <% @competition = Competition.find_by(status: "Ongoing") %>

          <% if @competition != nil %>
          <%= link_to "End Training Session", edit_competition_path(@competition.id), class: "btn btn-danger", method: :get %>
          <% end %>
        <% elsif @role == "Office of Finance" %>
            <br>
              <%= link_to "Generate Balance Report", report_varsity_members_path(:format => :pdf), class: "btn btn-primary"%>
              <%= link_to "Email Balance 
              Report", report_email_varsity_members_path(:format => :pdf), class: "btn btn-primary"%>
      <% end %>
<% end %>

app/views/varsity_members/new.html.erb
<h1>New Varsity Member</h1>

<%= render 'form' %>

<p style="margin: 1% 0 0 1.4%;"><%= link_to 'Back', varsity_members_path, class: "btn btn-default" %></p>

app/views/varsity_members/report.pdf.erb
<p style="text-align: right;"><%= wicked_pdf_image_tag 'ads_logo.png', :size => '200x75' %></p>

<h1 style="text-align: center;">ATENEO DEBATE SOCIETY</h1>
<h2 style="text-align: center;">BALANCE REPORT</h2>

<p><strong>Date: </strong><%= Time.now.strftime("%m/%d/%Y") %></p>

<div class="responsive">
  <table class="table table-striped" style="border-spacing: 17px 10px; border: 1px solid black; ">
    <thead>
      <tr>
        <th>ID</th>
        <th>Last Name</th>
        <th>Varsity Track</th>
        <th>Debater Position</th>
        <th>Acquired QP</th>
        <th>Total Debt</th>
        <th colspan="10"></th>
      </tr>
    </thead>

    <tbody>
      <% @varsity_members.each do |varsity_member| %>
        <tr>
          <td><%= varsity_member.vm_id %></td>
          <td><%= varsity_member.last_name %></td>
          <td><%= varsity_member.varsity_track %></td>
          <td><%= varsity_member.debater_position %></td>
          <td style= "text-align: right;"><%= number_with_precision(varsity_member.total_acquired_quota_points, precision: 2, delimiter: ',') %></td>
          <td style= "text-align: right;"><%= number_to_currency(varsity_member.total_debt, :unit => "Php") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/varsity_members/report_email.html.erb
<p style="text-align: right;"><%= wicked_pdf_image_tag 'ads_logo.png', :size => '200x75' %></p>

<h1 style="text-align: center;">ATENEO DEBATE SOCIETY</h1>
<h2 style="text-align: center;">BALANCE REPORT</h2>

<p><strong>Date: </strong><%= Time.now.strftime("%m/%d/%Y") %></p>

<div class="responsive">
  <table class="table table-striped" style="border-spacing: 17px 10px; border: 1px solid black; ">
    <thead>
      <tr>
        <th>ID</th>
        <th>Last Name</th>
        <th>Varsity Track</th>
        <th>Debater Position</th>
        <th>Acquired QP</th>
        <th>Total Debt</th>
        <th colspan="10"></th>
      </tr>
    </thead>

    <tbody>
      <% @varsity_members.each do |varsity_member| %>
        <tr>
          <td><%= varsity_member.vm_id %></td>
          <td><%= varsity_member.last_name %></td>
          <td><%= varsity_member.varsity_track %></td>
          <td><%= varsity_member.debater_position %></td>
          <td style= "text-align: right;"><%= number_with_precision(varsity_member.total_acquired_quota_points, precision: 2, delimiter: ',') %></td>
          <td style= "text-align: right;"><%= number_to_currency(varsity_member.total_debt, :unit => "Php") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/varsity_members/report_email.pdf.erb
<p style="text-align: right;"><%= wicked_pdf_image_tag 'ads_logo.png', :size => '200x75' %></p>

<h1 style="text-align: center;">ATENEO DEBATE SOCIETY</h1>
<h2 style="text-align: center;">BALANCE REPORT</h2>

<p><strong>Date: </strong><%= Time.now.strftime("%m/%d/%Y") %></p>

<div class="responsive">
  <table class="table table-striped" style="border-spacing: 17px 10px; border: 1px solid black; ">
    <thead>
      <tr>
        <th>ID</th>
        <th>Last Name</th>
        <th>Varsity Track</th>
        <th>Debater Position</th>
        <th>Acquired QP</th>
        <th>Total Debt</th>
        <th colspan="10"></th>
      </tr>
    </thead>

    <tbody>
      <% @varsity_members.each do |varsity_member| %>
        <tr>
          <td><%= varsity_member.vm_id %></td>
          <td><%= varsity_member.last_name %></td>
          <td><%= varsity_member.varsity_track %></td>
          <td><%= varsity_member.debater_position %></td>
          <td style= "text-align: right;"><%= number_with_precision(varsity_member.total_acquired_quota_points, precision: 2, delimiter: ',') %></td>
          <td style= "text-align: right;"><%= number_to_currency(varsity_member.total_debt, :unit => "Php") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/varsity_members/report_email.text.erb
Listing Varsity Members

        Varsity Track
        Debater Position
        Acquired QP
        Total Debt

      <% @varsity_members.each do |varsity_member| %>
         <%= varsity_member.vm_id %>
         <%= varsity_member.last_name %>
         <%= varsity_member.varsity_track %>
         <%= varsity_member.debater_position %>
         <%= number_with_precision(varsity_member.total_acquired_quota_points, precision: 2, delimiter: ',') %>
         <%= number_to_currency(varsity_member.total_debt, :unit => "Php") %>
      <% end %>

app/views/varsity_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @varsity_member.vm_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @varsity_member.first_name %> <%= @varsity_member.last_name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @varsity_member.year %>
</p>

<p>
  <strong>Course:</strong>
  <%= @varsity_member.course %>
</p>

<p>
  <strong>Contact Number:</strong>
  <%= @varsity_member.contact_number %>
</p>

<p>
  <strong>Email Address:</strong>
  <%= @varsity_member.email_address %>
</p>

<p>
  <strong>Varsity Track:</strong>
  <%= @varsity_member.varsity_track %>
</p>

<p>
  <strong>Debater Position:</strong>
  <%= @varsity_member.debater_position %>
</p>

<%= link_to 'Edit', edit_varsity_member_path(@varsity_member), class: "btn btn-default" %>
<%= link_to 'Back', varsity_members_path, class: "btn btn-default" %>

app/views/varsity_members/update.html.erb
<h1>VarsityMembers#update</h1>
<p>Find me in app/views/varsity_members/update.html.erb</p>