config/routes.rb
Rails.application.routes.draw do

  resources :pages

  root 'pages#index'
   get "/varsity_members/report", to: "varsity_members#report", as: :report_varsity_members
   get "/varsity_members/report_email", to: "varsity_members#report_email", as: :report_email_varsity_members
  resources :varsity_members
   get "/debt_settlements/:id/confirm", to: "debt_settlements#confirm", as: :category_confirm
  resources :tryout_intents
  resources :training_activities
  resources :debt_settlements
  resources :competitions
  resources :contingents
  resources :acquired_quota_points
  resources :competition_debts
  devise_for :officer_in_charges, :controllers => { :registrations => "registrations" } #, :path_names => { :sign_up => "debate" }
  devise_scope :officer_in_charge do
     get 'debate' => 'devise/registrations#new', :as => :new_officer_in_charges_registration 
     post 'debate' => 'devise/registrations#create', :as => :officer_in_charges_registration
  end
  match '/officer_in_charges/:id' => 'officer_in_charges#destroy', :via => :delete, :as => :admin_destroy_user
  get "/officer_in_charges/index", to: "officer_in_charges#index", as: :officer_in_charges
  get "/officer_in_charges/make", to: "officer_in_charges#make", as: :make_officer_in_charges

end

app/models/competition.rb
class Competition < ActiveRecord::Base
	has_many :competition_debts
	has_many :contingents
	has_many :activity_members


	STATUS = ["Ongoing", "Upcoming", "Processing", "Completed"]
  #validation of custom always goes first
  #current_user method cannot be accessed in model
	validates :name, length: { maximum: 30}
	validates :number_of_contingent, length: { maximum: 3 }, numericality: true
	validates :arqp_contingent_debater, length: { maximum: 4 }, numericality: true
	validates :arqp_contingent_adjudicator, length: { maximum: 4 }, numericality: true
	validates :arqp_non_contingent, length: { maximum: 4 }, numericality: true
	validates :status, presence: true, inclusion: { in: STATUS }
	validates :end_date, presence: true
	validates :start_date, presence: true
	validates :quota_point_monetary_value, length: { maximum: 4 }, numericality: true

	validate :cannot_be_invalid
  validate :date_validation

	def cannot_be_invalid
    if self.name == "" 
          errors.add(:name, "Cannot be blank!")
    end
    if !self.number_of_contingent.nil?
	 	   if self.number_of_contingent <= 0
	       errors.add(:number_of_contingent, "Quantity must not be negative!")
	     end
    end

    if !self.arqp_contingent_debater.nil?
	    if self.arqp_contingent_debater <= 0
	      errors.add(:arqp_contingent_debater, "Quantity must not be negative!")
	    end
    end

    if !self.arqp_contingent_adjudicator.nil?
	    if self.arqp_contingent_adjudicator <= 0
	      errors.add(:arqp_contingent_adjudicator, "Quantity must not be negative!")
	    end
    end

    if !self.arqp_non_contingent.nil?
	    if self.arqp_non_contingent <= 0
	      errors.add(:arqp_non_contingent, "Quantity must not be negative!")
	    end
    end

    if !self.quota_point_monetary_value.nil?
	    if self.quota_point_monetary_value <= 0
	      errors.add(:quota_point_monetary_value, "Quantity must not be negative!")
	    end
    end

	end

  validate :status_check
  def status_check
      competition = Competition.find_by(status: "Ongoing")

      if self.status == "Ongoing" && competition != nil
        errors.add(:status, "A competition is currently ongoing")
      end

      #if self.status == "Completed" 
      #   raise "Error: Competition is alredy completed"
      #   errors.add(:status, "Competition is alredy completed")
      # end
  end
	 #  def ongoing!
  #   if self.status == "Ongoing"
  #     raise "ERROR: Competition already Ongoing" 
  #   else
  #     self.update!(status: "Ongoing")
  #   end 
  # end

  # def completed!
  #   if self.status == "Completed"
  #     raise "ERROR: Competition already Completed" 
  #   else
  #     self.update!(status: "Completed")
  #   end 
  # end

  # def upcoming!
  #     if self.status == "Upcoming"
  #       raise "ERROR: Competition already Upcoming" 
  #     else
  #       self.update!(status: "Upcoming")
  #     end
  # end

  # def processing!
  #   result = false
  #     if self.status == "Processing" || self.status == "Completed"
  #       raise "ERROR: Competition already Processing" 
  #       return result = false
  #     else
  #       self.update!(status: "Processing")
  #       return result = true
  #     end
  # end

  after_update :total_debt, if:  Proc.new { |competition| competition.status == "Processing" } #{competition.presidential_approval_status == "processing"}
  
  def total_debt 
    temp = 0
    debt = 0
      VarsityMember.all.each do |vmember|
      #vmember.activity_members.each do |amember|
         
         #competition = Competition.find(amember.competition_id)
         #competition = Competition.find_by(status: "Processing")
         #vm = VarsityMember.find(amember.varsity_member_id)
         if vmember.debater_position == "Contingent Debater"

          temp = self.arqp_contingent_debater - vmember.total_acquired_quota_points
            if temp > 0 
                debt = temp * self.quota_point_monetary_value
                debt_total = vmember.total_debt + debt
                vmember.update(:total_debt => debt_total)      
            end
        
        elsif vmember.debater_position == "Contingent Adjudicator"

              temp = self.arqp_contingent_adjudicator - vmember.total_acquired_quota_points
            if temp > 0 
                debt = temp * self.quota_point_monetary_value
                debt_total = vmember.total_debt + debt
                vmember.update(:total_debt => debt_total)
            end

        elsif vmember.debater_position == "Non-contingent"

              temp = self.arqp_non_contingent - vmember.total_acquired_quota_points
            if temp > 0 
                debt = temp * self.quota_point_monetary_value
                debt_total = vmember.total_debt + debt
                vmember.update(:total_debt => debt_total)
            end
        end
          vmember.update(:total_acquired_quota_points => 0)
          vmember.update(:debater_position => "Non-contingent")
          self.update!(status: "Completed")
    end


  end

  def to_s
    self.name
  end 

  def date_validation
    if end_date <= start_date
      errors.add(:start_date, "Date is inconsistent")
    end
  end

end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
   load_and_authorize_resource
  def index
    if params[:status] == "Ongoing"
      @competitions = Competition.where("status = ?", params[:status])
    elsif params[:status] == "Completed"
      @competitions = Competition.where("status = ?", params[:status])
    elsif params[:status] == "Upcoming"
      @competitions = Competition.where("status = ?", params[:status])
    else
      @competitions = Competition.all 
    end
    
    render(:template => "competitions/index")
  end

  def show
    @competition = Competition.find(params[:id])
  end

  def new
    @competition = Competition.new

    render(:template => "competitions/new")
  end

  def create
    @competition = Competition.new(competition_params)

    if @competition.save
      redirect_to competition_path(@competition.id)
    else
      render(:template => "competitions/new")
    end
  end

  def edit
    @competition = Competition.find(params[:id])

    render(:templace => "competitions/edit")
  end

  def update
    @competition = Competition.find(params[:id])

    if @competition.update(competition_params)
      redirect_to competition_path(@competition)
    else
      render(:template => "competitions/edit")
    end
  end

  def destroy
    @competition = Competition.find(params[:id])
    @competition.destroy!
    redirect_to competitions_path
  end

  def competition_params
    params.require(:competition).permit!
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= simple_form_for(@competition) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: 'Competition Name' %>
  </div>

  <div class="form-inputs">
    <%= f.input :number_of_contingent, label: 'Number of members in the contingent', placeholder: '0' %>
  </div>

  <div class="form-inputs">
    <%= f.input :arqp_contingent_debater, :label => "Assigned Required Quota Points for Contingent Debater", placeholder: '0.0' %>
  </div>

  <div class="form-inputs">
    <%= f.input :arqp_contingent_adjudicator, :label => "Assigned Required Quota Points for Contingent Adjudicator", placeholder: '0.0' %>
  </div>

  <div class="form-inputs">
    <%= f.input :arqp_non_contingent, :label => "Assigned Required Quota Points for Non-Contingent", placeholder: '0.0' %>
  </div>

  <div class="form-inputs">
    <%= f.input :status, :as => :select, priority: [ "Ongoing" ], :collection => Competition::STATUS, :label => "Status", :include_blank => false  %>
  </div>

  <div class="form-inputs">
    <%= f.label :start_date, "Start Date" %>
    <%= f.date_select :start_date, :selected => Date.today, :order => [ :day, :month, :year] %>
  </div>

  <div class="form-inputs">
    <%= f.label :end_date, "End Date" %>
    <%= f.date_select :end_date, :selected => Date.today + 1, :order => [ :day, :month, :year] %>
  </div>

  <div class="form-inputs">
    <%= f.input :quota_point_monetary_value, placeholder: '0.00' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, data: { confirm: 'Are you sure?'}%>
  </div>
<% end %>

app/views/competitions/create.html.erb
<h1>Competitions#create</h1>
<p>Find me in app/views/competitions/create.html.erb</p>

app/views/competitions/destroy.html.erb
<h1>Competitions#destroy</h1>
<p>Find me in app/views/competitions/destroy.html.erb</p>

app/views/competitions/edit.html.erb
<h1>Editing Competition</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', competitions_path, class: "btn btn-default" %>

app/views/competitions/index.html.erb
<h1>Listing Competitions</h1>
<p>
<a class="btn btn-default" href="/competitions">All</a>
<%= link_to "Ongoing", competitions_path(:status=>"Ongoing"), class: "btn btn-default" %>
<%= link_to "Completed", competitions_path(:status=>"Completed"), class: "btn btn-default" %>
<%= link_to "Upcoming", competitions_path(:status=>"Upcoming"), class: "btn btn-default" %> 
</p>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Name</th>
      <th style= "text-align: right;">Number of Contingent</th>
      <th style= "text-align: right;">Required QP for CD</th>
      <th style= "text-align: right;">Required QP for CA</th>
      <th style= "text-align: right;">Required QP for NC</th>
      <th>Status</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th style= "text-align: right;">Quota Point Monetary Value</th>
      <th colspan="9"></th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.name %></td>
        <td style= "text-align: right;"><%= competition.number_of_contingent %></td>
        <td style= "text-align: right;"><%= number_with_precision(competition.arqp_contingent_debater, precision: 2, delimiter: ',') %></td>
        <td style= "text-align: right;"><%= number_with_precision(competition.arqp_contingent_adjudicator, precision: 2, delimiter: ',') %></td>
        <td style= "text-align: right;"><%= number_with_precision(competition.arqp_non_contingent, precision: 2, delimiter: ',') %></td>
        <td><%= competition.status %></td>
        <td><%= competition.start_date %></td>
        <td><%= competition.end_date %></td>
        <td style= "text-align: right;"><%= number_to_currency(competition.quota_point_monetary_value, :unit => "Php") %></td>
        <td><%= link_to 'Show', competition, class: "btn btn-primary" %></td>

        <% if officer_in_charge_signed_in? %>
              <% @role = Role.find(current_officer_in_charge.role_id).name %>

              <% if @role == "Office of Training and Varsity"%>
                  <td><%= link_to 'Edit', edit_competition_path(competition), class: "btn btn-warning" %></td>
              <% end %>
        <% end %>

        <td><%= link_to 'Delete', competition, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if officer_in_charge_signed_in? %>
      <% @role = Role.find(current_officer_in_charge.role_id).name %>

      <% if @role == "Office of Training and Varsity"%>
          <%= link_to 'New Competition', new_competition_path, class: "btn btn-default" %>
      <% end %>
<% end %>

app/views/competitions/new.html.erb
<h1>New Competition</h1>

<%= render 'form' %>

<p style="margin-top: 1%;"><%= link_to 'Back', competitions_path, class: "btn btn-default" %></p>

app/views/competitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @competition.name %>
</p>

<p>
  <strong>Number of Contingent:</strong>
  <%= @competition.number_of_contingent %>
</p>

<p>
  <strong>Required Quota Points for Contingent Debater:</strong>
  <%= number_with_precision(@competition.arqp_contingent_debater, precision: 2, delimiter: ',') %>
</p>

<p>
  <strong>Required Quota Points for Contingent Adjudicator:</strong>
  <%= number_with_precision(@competition.arqp_contingent_adjudicator, precision: 2, delimiter: ',') %>
</p>

<p>
  <strong>Required Quota Points for Non-Contingent:</strong>
  <%= number_with_precision(@competition.arqp_non_contingent, precision: 2, delimiter: ',') %>
</p>

<p>
  <strong>Status:</strong>
  <%= @competition.status %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @competition.start_date %>
</p>

<p>
  <strong>End Date:</strong>
  <%= @competition.end_date %>
</p>

<p>
  <strong>Quota Point Monetary Value:</strong>
  <%= number_to_currency(@competition.quota_point_monetary_value, :unit => "Php") %>
</p>

<%= link_to 'Edit', edit_competition_path(@competition), class: "btn btn-default" %>
<%= link_to 'Back', competitions_path, class: "btn btn-default" %>

app/views/competitions/update.html.erb
<h1>Competitions#update</h1>
<p>Find me in app/views/competitions/update.html.erb</p>