config/routes.rb
Rails.application.routes.draw do

  resources :pages

  root 'pages#index'
   get "/varsity_members/report", to: "varsity_members#report", as: :report_varsity_members
   get "/varsity_members/report_email", to: "varsity_members#report_email", as: :report_email_varsity_members
  resources :varsity_members
   get "/debt_settlements/:id/confirm", to: "debt_settlements#confirm", as: :category_confirm
  resources :tryout_intents
  resources :training_activities
  resources :debt_settlements
  resources :competitions
  resources :contingents
  resources :acquired_quota_points
  resources :competition_debts
  devise_for :officer_in_charges, :controllers => { :registrations => "registrations" } #, :path_names => { :sign_up => "debate" }
  devise_scope :officer_in_charge do
     get 'debate' => 'devise/registrations#new', :as => :new_officer_in_charges_registration 
     post 'debate' => 'devise/registrations#create', :as => :officer_in_charges_registration
  end
  match '/officer_in_charges/:id' => 'officer_in_charges#destroy', :via => :delete, :as => :admin_destroy_user
  get "/officer_in_charges/index", to: "officer_in_charges#index", as: :officer_in_charges
  get "/officer_in_charges/make", to: "officer_in_charges#make", as: :make_officer_in_charges

end

app/models/tryout_intent.rb
class TryoutIntent < ActiveRecord::Base
	validates :date, presence: true
	validates :competition_id, presence: true
	has_one :contingent

	has_many :tryout_members, :dependent => :destroy
	accepts_nested_attributes_for :tryout_members

	belongs_to :competition

	def to_s
		self.competition.name
	end


	after_create :create_contingent

  	def create_contingent
  		Contingent.create(tryout_intent_id: self.id)
  	end

  	 after_destroy :delete_contingent

  	private
    def delete_contingent
      Contingent.destroy(self.id)
    end
end

app/controllers/tryout_intents_controller.rb
class TryoutIntentsController < ApplicationController
   load_and_authorize_resource
  def index
    @tryout_intents = TryoutIntent.all 

    render(:template => "tryout_intents/index")
  end

  def show
    @tryout_intent = TryoutIntent.find(params[:id])
  end

  def new
    @tryout_intent = TryoutIntent.new

    render(:template => "tryout_intents/new")
  end

  def create
    @tryout_intent = TryoutIntent.new(tryout_intent_params)

    if @tryout_intent.save
      redirect_to tryout_intent_path(@tryout_intent.id)
    else
      render(:template => "tryout_intents/new")
    end
  end

  def edit
    @tryout_intent = TryoutIntent.find(params[:id])

    render(:templace => "tryout_intents/edit")
  end

  def update
    @tryout_intent = TryoutIntent.find(params[:id])

    if @tryout_intent.update(tryout_intent_params)
      redirect_to tryout_intent_path(@tryout_intent)
    else
      render(:template => "tryout_intents/edit")
    end
  end

  def destroy
    @tryout_intent = TryoutIntent.find(params[:id])
    @tryout_intent.destroy!
    redirect_to tryout_intents_path
  end 

  def tryout_intent_params
    params.require(:tryout_intent).permit!
  end
end

app/helpers/tryout_intents_helper.rb
module TryoutIntentsHelper
end

app/views/tryout_intents/_form.html.erb
<%= simple_nested_form_for(@tryout_intent) do |f| %>
  <%= f.error_notification %>

<% if Competition.find_by(status: "Ongoing") == nil && Competition.find_by(status: "Upcoming") == nil %>

  <p> There is no ongoing competition! </p>
  <% else %>

  <div class="form-inputs">
    <%= f.date_select :date, :selected => Date.today, :order => [ :day, :month, :year] %>
  </div>

  <div class="form-inputs">
    <%= f.association :competition, :as => :collection_select, collection: Competition.where("status != 'Completed'"), :include_blank => false %>
  </div>

    <div class="form-inputs">
    <%= f.fields_for :tryout_members do |ff|%>
    <%= ff.association :varsity_member, :as => :collection_select, collection: VarsityMember.where("total_debt = 0"), :include_blank => false %>
    <%= ff.input :debater_position, :as => :select, :collection => TryoutMember::POSITION, :include_blank => false %>
      <p style="margin-bottom: 1%;"><%= ff.link_to_remove "Remove" , class: "btn btn-danger" %></p>
    <% end %>
    <p><%= f.link_to_add "Add a member", :tryout_members, class: "btn btn-default" %></p>
  </div>

  <div class="form-actions">
    <%= f.button :submit, data: { confirm: 'Are you sure?'}%>
  </div>
<% end %>
<% end %>

app/views/tryout_intents/create.html.erb
<h1>TryoutIntents#create</h1>
<p>Find me in app/views/tryout_intents/create.html.erb</p>

app/views/tryout_intents/destroy.html.erb
<h1>TryoutIntents#destroy</h1>
<p>Find me in app/views/tryout_intents/destroy.html.erb</p>

app/views/tryout_intents/edit.html.erb
<h1>Editing Tryout Intent</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back', tryout_intents_path, class: "btn btn-default" %>

app/views/tryout_intents/index.html.erb
<h1>Listing Tryouts</h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Comeptition</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @tryout_intents.each do |tryout_intent| %>
      <tr>
        <td><%= tryout_intent.date %></td>
        <td><%= tryout_intent.competition.to_s %></td>
        <td><%= link_to 'Show', tryout_intent, class: "btn btn-primary" %></td>

        <% if officer_in_charge_signed_in? %>
              <% @role = Role.find(current_officer_in_charge.role_id).name %>

              <% if @role == "Office of Training and Varsity"%>
                  <td><%= link_to 'Edit', edit_tryout_intent_path(tryout_intent), class: "btn btn-warning" %></td>
                  <td><%= link_to 'Delete', tryout_intent, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
              <% end %>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if officer_in_charge_signed_in? %>
      <% @role = Role.find(current_officer_in_charge.role_id).name %>

      <% if @role == "Office of Training and Varsity"%>
          <%= link_to 'Register for Tryouts', new_tryout_intent_path, class: "btn btn-default" %>
      <% end %>
<% end %>

app/views/tryout_intents/new.html.erb
<h1>New Tryout Intent</h1>

<%= render 'form' %>

<p style="margin-top: 1%;"><%= link_to 'Back', tryout_intents_path, class: "btn btn-default" %></p>

app/views/tryout_intents/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Date:</strong>
  <%= @tryout_intent.date %>
</p>

<p>
  <strong>Competition:</strong>
  <%= @tryout_intent.competition.to_s %>
</p>

  <strong>Tryout Members:</strong> 
</p>

    <table style="width: 100%;">
    <tr>
      <th>Name</th>
      <th>Position</th>
    </tr>
    <% @tryout_intent.tryout_members.each do |member| %>
      <tr>
        <td><%= member.varsity_member.to_s%></td>
        <td><%= member.debater_position%></td>
      </tr>
    <% end %>
  </table>

<%= link_to 'Edit', edit_tryout_intent_path(@tryout_intent), class: "btn btn-default" %>
<%= link_to 'Back', tryout_intents_path, class: "btn btn-default" %>

<br>

<% if officer_in_charge_signed_in? %>
      <% @role = Role.find(current_officer_in_charge.role_id).name %>

      <% if @role == "Office of Training and Varsity"%>
          <p style="margin-top: 1%;"><%= link_to 'End Tryouts', edit_contingent_path(@tryout_intent.id), class: "btn btn-danger" %></p>
      <% end %>
<% end %>

app/views/tryout_intents/update.html.erb
<h1>TryoutIntents#update</h1>
<p>Find me in app/views/tryout_intents/update.html.erb</p>