config/routes.rb
Rails.application.routes.draw do

  resources :pages

  root 'pages#index'
   get "/varsity_members/report", to: "varsity_members#report", as: :report_varsity_members
   get "/varsity_members/report_email", to: "varsity_members#report_email", as: :report_email_varsity_members
  resources :varsity_members
   get "/debt_settlements/:id/confirm", to: "debt_settlements#confirm", as: :category_confirm
  resources :tryout_intents
  resources :training_activities
  resources :debt_settlements
  resources :competitions
  resources :contingents
  resources :acquired_quota_points
  resources :competition_debts
  devise_for :officer_in_charges, :controllers => { :registrations => "registrations" } #, :path_names => { :sign_up => "debate" }
  devise_scope :officer_in_charge do
     get 'debate' => 'devise/registrations#new', :as => :new_officer_in_charges_registration 
     post 'debate' => 'devise/registrations#create', :as => :officer_in_charges_registration
  end
  match '/officer_in_charges/:id' => 'officer_in_charges#destroy', :via => :delete, :as => :admin_destroy_user
  get "/officer_in_charges/index", to: "officer_in_charges#index", as: :officer_in_charges
  get "/officer_in_charges/make", to: "officer_in_charges#make", as: :make_officer_in_charges

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <%= javascript_include_tag :defaults %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ateneo Debate Society</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/simple-sidebar.css" rel="stylesheet">

    <link href="css/ads.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <% if officer_in_charge_signed_in? %>
        <% @role = Role.find(current_officer_in_charge.role_id).name %>
        <div id="wrapper">
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">

                  <li>
                    <p style="color: white; letter-spacing: 2px;">ATENEO <span style="color: orange;">DEBATE</span> SOCIETY</p>
                  </li>
                  

                  <p style="color: white; padding-left: 6.5%;">
                    <strong>Email</strong>: <%=current_officer_in_charge.email%>
                  </p>

                  <p style="color: white; padding-left: 6.5%;">
                    <strong>User Type</strong>: <%= @role%>
                  </p>

            <% if @role== "Office of Training and Varsity" %>
                    <li>
                        <%= link_to "Varsity Members", varsity_members_path %>
                    </li>   
                    <li>
                        <%= link_to "Competitions", competitions_path %>
                    </li>                             
                    <li>
                        <%= link_to "Contingents", contingents_path %>
                    </li>
                    <li>
                        <%= link_to "Training Activities", training_activities_path %>
                    </li>
                    <li>
                        <%= link_to "Tryout Intent", tryout_intents_path %>
                    </li>
    		        <li>
                        <%= link_to "Acquired Quota Points", acquired_quota_points_path %>
                    </li>
                    <li style="margin-top: 85%;">
                        <%= link_to "Sign out", destroy_officer_in_charge_session_path%>
                    </li>
                    <%= image_tag("logo_orange.png", :alt => "") %>
                </ul>
            </div>

            <% elsif @role == "Office of Finance" %>
                    <li>
                        <%= link_to "Debt Settlements", debt_settlements_path %>
                    </li>
                    <li>
                        <%= link_to "Competition Debt", competition_debts_path %>
                    </li>
                    <li>
                        <%= link_to "Varsity Members", varsity_members_path %>
                    </li>
                    <li style="margin-top: 140%;">
                        <%= link_to "Sign out", destroy_officer_in_charge_session_path%>
                    </li>
                    <%= image_tag("logo_orange.png", :alt => "") %>
                </ul>
            </div>

            <% elsif @role == "Administrator" %>
                    <li>
                        <%= link_to "Officers In Charge", officer_in_charges_path %>
                    </li>
                    <li>
                        <%= link_to "Acquired Quota Points", acquired_quota_points_path %>
                    </li>
                    <li>
                        <%= link_to "Debt Settlements", debt_settlements_path %>
                    </li>
                    <li>
                        <%= link_to "Contingents", contingents_path %>
                    </li>
                    <li>
                        <%= link_to "Competitions", competitions_path %>
                    </li>
                    <li>
                        <%= link_to "Training Activities", training_activities_path %>
                    </li>
                    <li>
                        <%= link_to "Varsity Members", varsity_members_path %>
                    </li>
                    <li>
                        <%= link_to "Tryout Intent", tryout_intents_path %>
                    </li>
                    <li style="margin-top: 60%;">
                        <%= link_to "Sign out", destroy_officer_in_charge_session_path %>
                    </li>
                    <%= image_tag("logo_orange.png", :alt => "") %>
                </ul>
            </div>

        <% end %>
            
            <!-- /#sidebar-wrapper -->

            <!-- Page Content -->
            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <%= yield %> 
                            <!-- <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a> -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- /#page-content-wrapper -->

        </div>

    <% else %>
        <body style="background-color: black;">
            <div class="col-lg-4">
            </div>
            <div class="col-lg-4">
                <p style="text-align: center; margin-top: 30%;"><%= image_tag("logo_orange.jpg", :alt => "") %></p>
                <%= yield %> 
            </div>
            <div class="col-lg-4">
            </div>
        </body>
          
    <% end %>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>